services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=PostgrespwD
    ports:
      - 5432:5432
    volumes:
      - pgdata2:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
volumes:
  pgdata2:
  mongodata:
