services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=PostgrespwD
    ports:
      - 5432:5432
    volumes:
      - pgdata2:/var/lib/postgresql/data
volumes:
  pgdata2:
