import type { Metadata } from 'next';
import './globals.css';
import Navbar from './nav/Navbar';

export const metadata: Metadata = {
  title: 'Carsties',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
